### ISSUE TITLE
Duplicate rows returned for the same object (due to duplicate TNS rows for same object)

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/lasair4#41]
The following query returns more than one result for the same object. I've added the watchlist ID and tns ID to highlight where the duplicates are happening.

```
SELECT objects.objectId,
       sherlock_classifications.classification,
       crossmatch_tns.tns_name,
       crossmatch_tns.type,
       CASE when objects.objectId = "ZTF22aamwznx" then "Very Good" END as "lightcurve_quality",
       watchlist_hits.wl_id,
       crossmatch_tns.id
       FROM objects,
            sherlock_classifications,
            watchlist_hits,
            crossmatch_tns
       WHERE objects.objectId=sherlock_classifications.objectId
       AND objects.objectId=watchlist_hits.objectId
       AND watchlist_hits.wl_id=1
       AND watchlist_hits.name=crossmatch_tns.tns_name
       AND objects.objectId in ( "ZTF22aamwznx")
       AND crossmatch_tns.type is not null;

+--------------+----------------+----------+-------+--------------------+-------+-------+
| objectId     | classification | tns_name | type  | lightcurve_quality | wl_id | id    |
+--------------+----------------+----------+-------+--------------------+-------+-------+
| ZTF22aamwznx | SN             | 2022mbg  |       | Very Good          |     1 | 97423 |
| ZTF22aamwznx | SN             | 2022mbg  | SN Ia | Very Good          |     1 | 98220 |
| ZTF22aamwznx | SN             | 2022mbg  | SN Ia | Very Good          |     1 | 99509 |
+--------------+----------------+----------+-------+--------------------+-------+-------+

```

A check of the TNS table shows where the duplicates are happening.

```
select * from crossmatch_tns where id in (97423, 98220, 99509)\G
*************************** 1. row ***************************
                 ra: 31.5124129
               decl: 29.7919945
           tns_name: 2022mbg
         tns_prefix: AT
           disc_mag: 16.17
    disc_mag_filter: r
               type: 
                  z: NULL
              hostz: NULL
          host_name: NULL
       ext_catalogs: NULL
      disc_int_name: ZTF22aamwznx
          disc_date: 2022-06-04 11:16:48.000000
  lastmodified_date: 2022-06-05 18:10:24.000000
             sender: ZTF
          reporters: C. Fremling (Caltech) on behalf of the Zwicky Transient Facility (ZTF) coll...
       source_group: ZTF
              htm16: 68596048339
lasairmodified_date: 2022-06-06 00:18:05
                 id: 97423
*************************** 2. row ***************************
                 ra: 31.5124129
               decl: 29.7919945
           tns_name: 2022mbg
         tns_prefix: SN
           disc_mag: 16.17
    disc_mag_filter: r
               type: SN Ia
                  z: 0.016238
              hostz: NULL
          host_name: NULL
       ext_catalogs: NULL
      disc_int_name: ZTF22aamwznx, ATLAS22qxn
          disc_date: 2022-06-04 11:16:48.000000
  lastmodified_date: 2022-06-19 11:46:34.000000
             sender: ZTF
          reporters: C. Fremling (Caltech) on behalf of the Zwicky Transient Facility (ZTF) coll...
       source_group: ZTF
              htm16: 68596048339
lasairmodified_date: 2022-06-20 00:18:06
                 id: 98220
*************************** 3. row ***************************
                 ra: 31.512458
               decl: 29.791981
           tns_name: 2022mbg
         tns_prefix: SN
           disc_mag: 16.17
    disc_mag_filter: r
               type: SN Ia
                  z: 0.016238
              hostz: NULL
          host_name: NULL
       ext_catalogs: NULL
      disc_int_name: ZTF22aamwznx, ATLAS22qxn, Gaia22ctq
          disc_date: 2022-06-04 11:16:48.000000
  lastmodified_date: 2022-07-03 16:55:34.000000
             sender: ZTF
          reporters: C. Fremling (Caltech) on behalf of the Zwicky Transient Facility (ZTF) coll...
       source_group: ZTF
              htm16: 68596048339
lasairmodified_date: 2022-07-04 00:10:05
                 id: 99509
3 rows in set (0.001 sec)
```

Here we can see that the disc_int_name gets concatenated by different survey names evert time a survey records the object. Hence we need to do a REPLACE operation when writing new TNS entries.
